language: python
python:
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r requirements.txt --use-mirrors
  - cp sublimall/local_settings_example.py sublimall/local_settings.py
script:
  - python manage.py test
